### ISSUE TITLE
Minor bugs in CS163-3A

### ISSUE THREAD

**Issue by tachithanhdanh** [hc22apcs2/hc22apcs2.github.io#46]
**Describe the bug**
In [CS162 - 3A First Student's Code](https://hc22apcs2.github.io/docs/CS162/b3a/#students-code):
- On `line 46`, `cur` was not declared in `void inputLL(Node*& pHead)`.
- On `line 53`, declaration of `x` shadows a previous local (shadowed declaration is at `line  41`).

**To Reproduce**
Steps to reproduce the behavior: Just compile the code.

**Expected behavior**
Compile error and warning if `-Wshadow` is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/75555549/232039485-a630dd5b-da12-42ab-b4f2-f42cbdc2182a.png)

**Comment by nhphucqt** [comment]
Fixed
